# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql
  encoding: utf8
  database: client_development
  pool: 5
  username: root
  password: 260493    
test:
  adapter: mysql
  encoding: utf8
  database: client_test
  pool: 5
  username: root
  password: 260493
production:
  adapter: mysql
  encoding: utf8
  database: client_production
  pool: 5
  username: root
  password: 260493


